### ISSUE TITLE
Poppler installation path not detected automatically in windows 

### ISSUE THREAD

**Issue by biprakanta** [Belval/pdf2image#101]
poppler path  None
Unable to get page count. Is poppler installed and in PATH?
Traceback (most recent call last):
  File "C:\Users\bpal\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2image\pdf2image.py", line 353, in _page_count
    proc = Popen(command, env=env, stdout=PIPE, stderr=PIPE)
  File "C:\Users\bpal\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\bpal\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bpal\My Documents\LiClipse Workspace\Language_detector\src\dev\pdf_to_image.py", line 48, in <module>
    pil_images = pdftopil()
  File "C:\Users\bpal\My Documents\LiClipse Workspace\Language_detector\src\dev\pdf_to_image.py", line 39, in pdftopil
    raise err
  File "C:\Users\bpal\My Documents\LiClipse Workspace\Language_detector\src\dev\pdf_to_image.py", line 34, in pdftopil
    pil_images = pdf2image.convert_from_path(PDF_PATH, dpi=DPI, output_folder=OUTPUT_FOLDER, first_page=FIRST_PAGE, last_page=LAST_PAGE, fmt=FORMAT, thread_count=THREAD_COUNT, userpw=USERPWD, use_cropbox=USE_CROPBOX, strict=STRICT  )
  File "C:\Users\bpal\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2image\pdf2image.py", line 80, in convert_from_path
    page_count = _page_count(pdf_path, userpw, poppler_path=poppler_path)
  File "C:\Users\bpal\AppData\Local\Programs\Python\Python37\lib\site-packages\pdf2image\pdf2image.py", line 358, in _page_count
    "Unable to get page count. Is poppler installed and in PATH?"
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?

**Comment by biprakanta** [comment]
After mentioning the poppler path in function explicitly it works
But I think it needs enhancement to detect it automatically

**Comment by Belval** [comment]
Does anything like that exists in Windows? To my knowledge the only way to make an executable accessible OS-wide is to use the PATH environment variable.

The only way to detect it automatically would be to scan the file system to find it, and that would be ridiculously prohibitive resource-wise.

If you have another idea I'm open to suggestions on this.

**Comment by SimplyLucKey** [comment]
I have an executable that is meant to be distributed to people with no python installed or any of the packages. I have imported in my code 

> from pdf2image.exceptions import (
    PDFInfoNotInstalledError,
    PDFPageCountError,
    PDFSyntaxError
)

but when I ran the executable on those computers, I still get the errors. Is there a way to resolve this issue through code? Or do I have to give these people instructions on adding poppler to PATH?

**Comment by Belval** [comment]
You would have to distribute the `libpoppler` dll with the `pdftoppm` executable packaged with your application.

In your code you can specify the path with something like `convert_from_path('your_pdf.pdf', poppler_path='.\poppler\bin')`

**Comment by SimplyLucKey** [comment]
> You would have to distribute the `libpoppler` dll with the `pdftoppm` executable packaged with your application.
> 
> In your code you can specify the path with something like `convert_from_path('your_pdf.pdf', poppler_path='.\poppler\bin')`

Sorry if this is obvious. Where could I find libpoppler dll?
For poppler_path, does the path have to be in the same directory as the executable? The pdfs are likely not in the same directory as my program.

**Comment by Belval** [comment]
No need to apologize, it is not obvious. I would advise that you include a step to build `poppler` from source in your CI, but in my experience it is non-trivial.

What you can do is used precompiled windows binaries such as these: https://blog.alivate.com.au/poppler-windows/

As for the poppler_path, what I personally like to do is to create a directory in my project directory that contains my binaries. You don't need to keep them in the same directory as the pdf files that you are converting.

```
your_project
| convert.py
 \ bin
  | poppler
   \ bin
```

Then call `convert_from_path` with `poppler_path` set to `.\bin\poppler\bin` and it should work.

**Comment by SimplyLucKey** [comment]
So what I've done is:
-Downloaded the latest poppler binary
-Put that entire folder in the folder with my python executable file
-Added poppler_path=```.\poppler-0.68.0\bin``` as one of the convert_from_path arguments

And I'm still getting the same error. 
Did I do something wrong?

**Comment by deepak223098** [comment]
@Belval 
Thanks for the info. Thats worked for. 
just extracted the poppler from the "https://blog.alivate.com.au/poppler-windows/" then put in correct location.
Example:
 pages = convert_from_path(path, poppler_path= r'D:\Study\Text_OCR\poppler-0.68.0\bin')

and its worked for me (y)

**Comment by abjidge** [comment]
> poppler_path= r'D:\Study\Text_OCR\poppler-0.68.0\bin'

worked thanks

**Comment by celsowm** [comment]
I've tried this:

```
import pdf2textlib, os, sys
from pathlib import Path

poppler_path = os.path.join(Path().absolute(),'vendor','poppler','bin')
env = os.environ.copy()

if env.get("LD_LIBRARY_PATH") is None:
    os.environ["LD_LIBRARY_PATH"] = poppler_path
    sys.path.append(poppler_path)

print(env.get("LD_LIBRARY_PATH"))
print(pdf2textlib.getText("pdfa.pdf","por"))  
```

But still not working :(

**Comment by deepak223098** [comment]
not sure that pdf2textlib module is for poppler:
try this:
import pytesseract
from pdf2image import convert_from_path
pages = convert_from_path(path, poppler_path=r'D:\Study\Text_OCR\poppler-0.68.0\bin')
image_counter  =0
def extractImageFromPDF():
for page in pages:
        # Declaring filename for each page of PDF as JPG
        filename = "pdf_image_page_" + str(image_counter) + ".jpg"
        page.save("output" + "\\" + filename, 'JPEG')
        image_counter = image_counter + 1
        print("Total Number {0} of the image fetched from the pdf \n ".format(image_counter - 1))

def read_saved_image(out_path):
    all_image = []
    config = ('-l eng --oem 1 --psm 3')
    for d, _, f in os.walk(out_path):
        for i in f:
            if i.endswith('.jpg'):
                all_image.append(os.path.join(out_path, i))
            # End if
    for im in all_image:
        # download tesseract.exe for windows use this path:
        # https://github.com/UB-Mannheim/tesseract/wiki
        pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe' 
        text = pytesseract.image_to_string(im, lang = 'eng',config=config)
        print("Fetched Text for {0} -- \n {1} \n ".format(im, text))


Hope it helps you for what you are looking for. (y)

**Comment by SamikhaAgarwal** [comment]
These pdf2image and pdftotext library backend requierment is Poppler, so you have to install

**conda install -c conda-forge poppler **

then the error will be resolved. and if still it won't work for you then you can follow http://blog.alivate.com.au/poppler-windows/ to install this library.

**Comment by Senzokuhle** [comment]
i had the same issue, and this solved it for me:

**convert_from_path(poppler_path=r'C:\Program Files\poppler-0.68.0\bin')**

**Comment by andres-pb** [comment]
@SamikhaAgarwal 
That worked for me, thanks! 
However, before installing the package from conda I installed poppler following http://blog.alivate.com.au/poppler-windows/ and store it in Program Files. Do I need both of them or having both is redundant?

**Comment by M-SOLITA** [comment]
http://blog.alivate.com.au/poppler-windows/ is gone

**Comment by rifazks** [comment]
is there any other way?this link is broken
