### ISSUE TITLE
pdf2image seems not to be thread safe

### ISSUE THREAD

**Issue by stavrakidis** [Belval/pdf2image#125]
Using multiprocessing.dummy.Pool I get sometimes the following error. This happens not very often and after hundreds of convertions, but it can happen.

I think it's due to the fact that generators (via _yield_) are not thread safe, and pdf2images uses two generators. So pdf2images is not thread safe.

``
Traceback (most recent call last):
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/site-packages/*****/__main__.py", line 7, in <module>
    ocr.convert_**********()
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/site-packages/*****/**********/ocr.py", line 63, in convert_**********
    convert_dir(path_pdf, path_text)
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/site-packages/*****/**********/ocr.py", line 34, in convert_dir
    pool.starmap(pdf2text, file_list)
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/site-packages/*****/**********/ocr.py", line 40, in pdf2text
    pages = pdf2image.convert_from_path(pdf_file, poppler_path=configuration.get_value('ocr', 'poppler'))
  File "/srv/shared/conda/***/envs/**************/lib/python3.8/site-packages/pdf2image/pdf2image.py", line 144, in convert_from_path
    thread_output_file = next(output_file)
ValueError: generator already executing
``

**Comment by Belval** [comment]
That's possible, I never used with with multiple threads, only with multiple processes.

I'll get a reproducible test case and issue a fix.

**Comment by Belval** [comment]
Test case written:

```
def test_multithread_conversion(self):
        start_time = time.time()
        files = ["./tests/test.pdf", ] * 50
        p = Pool(10)
        res = p.map(convert_from_path, files)
        self.assertTrue(len(res) == 50)
        print("test_multithread_conversion: {} sec".format(time.time() - start_time))
```

**Comment by Belval** [comment]
I created a pull request that addresses this issue. I will probably merge it and build the new package in the coming hours.

**Comment by Belval** [comment]
Version 1.12.0 is now live, you should not get this error message anymore. Please tell me if it fixed the bug you were experiencing.

**Comment by stavrakidis** [comment]
Seems to work. Great!

**Comment by Belval** [comment]
Excellent, feel free to open a new issue if you encounter another problem.
