### ISSUE TITLE
pdf2image.exceptions.PDFPageCountError: Unable to get page count.

### ISSUE THREAD

**Issue by jimmyxp01** [Belval/pdf2image#162]
```
try:
    from PIL import Image
except ImportError:
    import Image
import pytesseract
from pdf2image import convert_from_path

PDF_file = "test.pdf"
pytesseract.pytesseract.tesseract_cmd = r'C:\Users\Jitu\AppData\Local\Tesseract-OCR'

pages = convert_from_path(PDF_file,600, poppler_path=r"C:\Users\Jitu\Desktop\release\poppler-0.90.1\bin")
```
when i try this i get this error ! 

```
PS C:\Users\Jitu\Desktop\PDF PY> python -u "c:\Users\Jitu\Desktop\PDF PY\TRY_ocrmypdf.py"
Traceback (most recent call last):
  File "C:\Users\Jitu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pdf2image\pdf2image.py", line 462, in pdfinfo_from_path
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Jitu\Desktop\PDF PY\TRY_ocrmypdf.py", line 11, in <module>
    pages = convert_from_path(PDF_file,600, poppler_path=r"C:\Users\Jitu\Desktop\release\poppler-0.90.1\bin")
  File "C:\Users\Jitu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pdf2image\pdf2image.py", line 97, in convert_from_path
    page_count = pdfinfo_from_path(pdf_path, userpw, poppler_path=poppler_path)["Pages"]
  File "C:\Users\Jitu\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pdf2image\pdf2image.py", line 471, in pdfinfo_from_path
    raise PDFPageCountError(
pdf2image.exceptions.PDFPageCountError: Unable to get page count.
```
I'm using windows 10. help me

**Comment by Belval** [comment]
Hi! 

Do you have poppler installed on your system?

**Comment by jimmyxp01** [comment]
Yes i think so, actually I'm a beginner so i didn't know much, but i download poppler. Here is the file ``` poppler_path=r"C:\Users\Jitu\Desktop\release\poppler-0.90.1\bin" ```

**Comment by Belval** [comment]
Ok, so first things you need to check:

- Is it the right path to your PDF?
- When you open the cmd.exe on Windows, go to your poppler directory and run `pdfinfo your_file.pdf` what is the output?
- Are you running in a virtualenv/conda that could be messing with your path?

**Comment by jimmyxp01** [comment]
When i run pdfinfo. It's show's ``` the code execution cannot proceed because MSVCP140.dll  was not found. Reinstall the program my fix this problem. ``` 

Poppler version 0.90.1

**Comment by jimmyxp01** [comment]
I solve this. Poppler version 0.90.1 is not working , i use Poppler version 0.68.0.

Thank you
