### ISSUE TITLE
Page images generated twice with multiple threads

### ISSUE THREAD

**Issue by ochedru** [Belval/pdf2image#214]
I get 4 images when calling `convert_from_path()` on a 2-page PDF with `thread_count=2`.

It looks like a bug in the distribution of pages to threads.

In addition to too much work being done,  when using `output_file=some_generator()` to control page file names, we can also get rare and weird errors due, I guess, to concurrency issues because the same page image file is being written and read at the same time. For example (using 4 threads for more concurrency):

```python
import pdf2image

def _generator():
    while True:
        yield 'input'

while True:
    pdf2image.convert_from_path('2pages.pdf', ouput_folder='/tmp', fmt='png', thread_count=4, output_file=generator())
```

```
Traceback (most recent call last):
  File "/tmp/test.py", line 8, in test
    pdf2image.convert_from_path(path, output_folder=td, fmt='png',
  File "/usr/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 218, in convert_from_path
    images += _load_from_output_folder(
  File "/usr/lib/python3.9/site-packages/pdf2image/pdf2image.py", line 517, in _load_from_output_folder
    images.append(Image.open(os.path.join(output_folder, f)))
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 3023, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/tmp/input-2.png'
```

**Comment by Belval** [comment]
Interesting, were you able to reproduce the issue with every 2 page PDFs that you tried? It seems like a critical bug that would have been found by now, but I'll try to reproduce the issue on my side.

**Comment by Belval** [comment]
Was able to reproduce locally on Archlinux with Python 3.9, looking for root cause.

**Comment by Belval** [comment]
Root cause is somewhat simple, since the base filename is not unique across threads  when end up loading all the images N time. This should not be too hard to fix.

As far as your second point is concerned, there shouldn't be R/W concurrency issues as everything is written before the files are read so when reading we only have one process loading the images.

**Comment by Belval** [comment]
I will put this issue on hold as it is actually not easy to fix. Filenames generator for `output_file` should be returning a different filename when called as it is how we differentiate between the output of the various threads. While I could fix this by simply loading all the files once the processing is over, this would directly conflict with a different feature which allows for the output directory to not be empty. I cannot go back on that as it would essentially be breaking changes.

The only clean "fix" that is see is to disregard output_file and generate random uuids for each thread then rename each output file before returning. This would require some work that I might be able to do this week.

In the meantime, you can just use a generator with an incremental counter such as https://github.com/Belval/pdf2image/blob/master/pdf2image/generators.py#L41 which takes a prefix or you can just not pass the output_file and default to the UUID one.

FYI you can get the generated filename with `PIL.Image.filename` so the pattern should not matter all that much.

**Comment by ochedru** [comment]
Thank you for your quick answer! I will change my generator to get different filenames.
