### ISSUE TITLE
Exception: Unable to get page count

### ISSUE THREAD

**Issue by rajasimon** [Belval/pdf2image#23]
Great library @Belval When I play around with my pdf I encountered that several of my pdf throws below exception. Not all of them but some of them throws error. I don't know it because of my pdf unfortunately I can't able to show the pdf to you. 

Can you provide the hints where it went wrong. Or let me know if you want any input from me to resolve this issue. 

```
Traceback (most recent call last):
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/pdf2image/pdf2image.py", line 163, in __page_count
    return int(re.search(r'Pages:\s+(\d+)', out.decode("utf8", "ignore")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/simon/Workspace/floornet/floornet/cli.py", line 43, in convert_command
    image = convert_from_path(floor4, output_folder=path, fmt='png')
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/pdf2image/pdf2image.py", line 29, in convert_from_path
    page_count = __page_count(pdf_path, userpw)
  File "/home/simon/.local/share/virtualenvs/floornet-K8h42tkL/lib/python3.7/site-packages/pdf2image/pdf2image.py", line 165, in __page_count
    raise Exception('Unable to get page count.')
Exception: Unable to get page count.
```

**Comment by rajasimon** [comment]
Okay it gives this output.

```
Tagged:         no
UserProperties: no
Suspects:       no
Form:           none
JavaScript:     no
Pages:          1
Encrypted:      no
Page size:      842 x 1191 pts (A3)
Page rot:       0
File size:      918369 bytes
Optimized:      no
PDF version:    1.4
```

**Comment by Belval** [comment]
This recently closed issue had a similar problem. Can you repeat the steps described and see if it works?

https://github.com/Belval/pdf2image/issues/19

**Comment by lucasguerreiro** [comment]
I am having the same problem.
In my case the code runs normally at my local machine, but I get the error when running in Google App Engine.
I've read the related issue, but I am not using gunicorn.
I have installed poppler-data and popple-utils.
Am I missing something on GAE?

**Comment by Belval** [comment]
pdf2image uses `subprocess` to make calls to pdftoppm. If this [thread](https://stackoverflow.com/questions/17791739/alternative-to-python-subprocess-module-in-google-app-engine) is to be believed, you cannot use `subprocess` in Google App Engine as it only executes Python code.

**Comment by lucasguerreiro** [comment]
Hi @Belval , thanks for the feedback (and congrats for the lib).
I am relying on some answers that imply that GAE flexible may call shell scripts and I assume it may be ok with subprocess as well (https://stackoverflow.com/questions/45250717/cannot-import-subprocess-call-when-running-google-app-engine-locally   and    https://stackoverflow.com/questions/47447910/google-app-engine-to-run-shell-script-files).

Any chance you know any other setup (assuming subprocess may run on GAE flexible) that I might be missing?
Thanks again.

**Comment by Belval** [comment]
If pdfinfo and pdftoppm both work there isn't anything else that you need.

What is your exact stack trace and is it possible for you to provide the PDF that causes the error?

Also (if you can tell me) what other modules are you using beside `pdf2image` like `flask`?

**Comment by lucasguerreiro** [comment]
Answering to your last question, my requirements.txt has:
pika==0.12.0
google-api-core==1.2.0
google-auth==1.4.2
google-cloud-vision==0.31.1
googleapis-common-protos==1.5.3
jellyfish==0.6.1
grpcio==1.12.0
PyMySQL==0.8.0
Flask-SQLAlchemy==2.3.2
mysql-connector-python==8.0.11

The problem actually happens with any file, I try.
My stack trace is:

Traceback (most recent call last):
  File "/home/vmagent/app/pdf2image2.py", line 163, in __page_count
    return int(re.search(r'Pages:\s+(\d+)', out.decode("utf8", "ignore")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mainprocess.py", line 30, in <module>
    channel.start_consuming()
  File "/env/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1822, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/env/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 758, in process_data_events
    self._dispatch_channel_events()
  File "/env/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 521, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/env/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1445, in _dispatch_events
    evt.body)
  File "mainprocess.py", line 20, in callback
    process.analyze(request_id)
  File "/home/vmagent/app/process.py", line 422, in analyze
    results, score = detect_text_pdf(url, request_id)
  File "/home/vmagent/app/process.py", line 377, in detect_text_pdf
    pages = convert_from_path(uri, 500)
  File "/home/vmagent/app/pdf2image2.py", line 29, in convert_from_path
    page_count = __page_count(pdf_path, userpw)
  File "/home/vmagent/app/pdf2image2.py", line 165, in __page_count
    raise Exception('Unable to get page count.')
Exception: Unable to get page count.

**Comment by Belval** [comment]
Nothing out of ordinary here. To clarify, the error means that `pdfinfo` didn't write anything to stdout. If you wish to troubleshoot further, you can replace the `_` [here](https://github.com/Belval/pdf2image/blob/dd959154857ed3a07cd9778c63965cb6bc243360/pdf2image/pdf2image.py#L160) by `err` and print it.

It is highly probable that pdfinfo is writing something to stderr.

In the near future I will replace the rather useless 'Unable to get page count' with the stderr.

**Comment by lucasguerreiro** [comment]
Thanks Belval!
I could bypass it when forcing my page number AND downloading the files before converting them.
Strange thing is that I can't convert from URI, but it works locally. So, I will try to investigate how to do it on GAE...
Thank you again

**Comment by Belval** [comment]
Hey, while building a test case I found this comment in the sample app that may or may not apply to you.

![screenshot from 2018-07-31 20-02-15](https://user-images.githubusercontent.com/5399488/43493607-cdf90a58-94fc-11e8-962d-70e25a3d0392.png)

While the app doesn't explicitly use gunicorn, it seems to be running inside a gunicorn process.

**Comment by rajasimon** [comment]
@Belval My requirement changes over time and I'm not using the pdf2image as of now. Feel free to close this issue.

**Comment by markus7017** [comment]
you could fix the module 'av' issues by installing video support and PyAV
pip3 install preview-generator
brew install freetype imagemagick exiftool ffmpeg pkg-config    (for Mac)
