### ISSUE TITLE
Not possible to catch fonts missing error.

### ISSUE THREAD

**Issue by bpdev97** [Belval/pdf2image#37]
**Describe the bug**
If fonts are not found that are used within the pdf, an error will be thrown by pdftoppm. Currently, there is no way to catch this exception. This can result in a blank page(s) being created "successfully".

**To Reproduce**
Try to convert a pdf that contains a font that your system does not have installed.

**Expected behavior**
Suggesting you somehow return stderr to the user.

**Comment by Belval** [comment]
Interesting, could you provide a sample PDF to test a potential fix?

**Comment by bpdev97** [comment]
Are you familiar with docker? It's going to be hard to give you a test pdf as I have no idea what fonts you have on your system. But I could create an example script/pdf in a docker container for you.

**Comment by Belval** [comment]
Oh yeah a test case in a docker container would be awesome!

**Comment by bpdev97** [comment]
Cool, here's the docker container and steps to reproduce.

Start bash in the container. (This has your library and python 3 installed)
`docker run -it bpdev97:pdf2image-font-example /bin/bash`

Create a png from test.pdf
`pdftoppm -r 150 -png test.pdf out`

You should see a bunch of font missing errors. pdf2image masks these errors.

**Comment by Belval** [comment]
So I did a quick prototype:

    for uid, proc in processes:
        data, err = proc.communicate()

        if b"Couldn't find a font for" in err:
            raise MissingFontError()

        if output_folder is not None:
            images += __load_from_output_folder(output_folder, uid)
        else:
            images += parse_buffer_func(data)

Which returns:

    Traceback (most recent call last):
      File "test2.py", line 3, in <module>
        convert_from_path('../test.pdf')
      File "/app/pdf2image/pdf2image/pdf2image.py", line 71, in convert_from_path
        raise MissingFontError()
    pdf2image.exceptions.MissingFontError

But I dislike the reliance on someone at poppler not changing the error message...

**Comment by bpdev97** [comment]
I'll dig a little more, but I didn't see anything earlier that you could catch other than that error. I agree it sucks if you have to rely on them not changing the error message though.

**Comment by Belval** [comment]
I know the maintainers are active on IRC, I'll try to contact them.

You can expect a "fixed" version in the next few days.

**Comment by bpdev97** [comment]
I thought you could maybe use the exit code of `pdftoppm` but it appears to return 0 even though the man page says otherwise. Okay cool, thank you!

<img width="408" alt="screen shot 2018-12-11 at 10 54 39 pm" src="https://user-images.githubusercontent.com/10634312/49846142-cd3cc100-fd97-11e8-9f8f-725bfb77ebf0.png">

**Comment by Belval** [comment]
User tsdgeos recommended to open a bug so I'll do that, but in the mean time, most Linux installation do not ship with the last version of poppler to fixing it in a future version would yield very little value for most people. I'll probably go forward with matching text for this version and change the error handling should a more tasteful solution presents itself.

![screenshot from 2018-12-12 10-03-27](https://user-images.githubusercontent.com/5399488/49878291-343c9300-fdf5-11e8-8b2f-1c0b61c3f011.png)

**Comment by Belval** [comment]
Okay, so after diving into pdftoppm error output, I am afraid I do not want to raise the MissingFontError.

The thing is that pdftoppm is configured to use a fallback when something fishy is up with the font. People using pdftoppm right now could end up with new exceptions in their applications.

What I did is add a new `strict` parameter to the function call that you must set to `True`. If you want to catch the `MissingFontError` exception it will be under the `PDFSyntaxError` name and it can also be thrown if your PDF are malformed.

**Comment by bpdev97** [comment]
That will work, thanks!

**Comment by Belval** [comment]
Version 1.2.0 is now available on PyPi.

Feel free to close the issue once you ensured it works as expected.

Thank you.

**Comment by bpdev97** [comment]
Okay, I looked at your fix. That should work, however one improvement I would make is to also bubble up the error text in the exception.

**Comment by Belval** [comment]
Excellent idea, I will push an updated version as soon as I can.

**Comment by Belval** [comment]
Closing for lack of activity and I think this is reasonably fixed. Feel free to reopen if you experience related issues.
