### ISSUE TITLE
OSError Thrown When Corrupt Image Is Generated

### ISSUE THREAD

**Issue by maxshowarth** [Belval/pdf2image#44]
Have a script that is using pdf2image to process a large number of PDF files that are subsequently being OCR'ed. 

OSError: cannot identify image file seems to occur when pdf2image is trying to collect the outputted images: 

`  File "/opt/conda/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 196, in _load_from_output_folder
    images.append(Image.open(os.path.join(output_folder, f)))`

I was able to verify that the outputted image was unreadable on my local machine. 

Here is the full Traceback: 
```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "<ipython-input-4-04311ac4d4d9>", line 9, in doOCR
    timings = file.ocr()
  File "<ipython-input-1-c1e57a508011>", line 186, in ocr
    images = convert_from_path(self.tempFilePath, output_folder=tempImageDirectory, fmt="tif")
  File "/opt/conda/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 103, in convert_from_path
    images += _load_from_output_folder(output_folder, uid, in_memory=auto_temp_dir)
  File "/opt/conda/lib/python3.6/site-packages/pdf2image/pdf2image.py", line 196, in _load_from_output_folder
    images.append(Image.open(os.path.join(output_folder, f)))
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2657, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/storage/temp/74F13-0025_Radiometric Logs (S-3 to S-7).pdf/images/be3861fa-f942-4c95-9aa3-4ed16550fc48-4.tif'
"""

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
<ipython-input-5-8c10a9d0814b> in <module>
      1 startTime_ = datetime.datetime.now()
      2 p = Pool(12)
----> 3 p.map(doOCR, filesToOCR)
      4 
      5 while not q.empty():

/opt/conda/lib/python3.6/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    286         in a list that is returned.
    287         '''
--> 288         return self._map_async(func, iterable, mapstar, chunksize).get()
    289 
    290     def starmap(self, func, iterable, chunksize=None):

/opt/conda/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    668             return self._value
    669         else:
--> 670             raise self._value
    671 
    672     def _set(self, i, obj):

OSError: cannot identify image file '/storage/temp/someFile.tif'
```

**Comment by Belval** [comment]
What is the filename of the PDF you are converting? Also, can you test with version 1.0 if the issue existed back then?

**Comment by Belval** [comment]
Closing for lack of response. Feel free to reopen.
