### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by rafaleo** [Belval/pdf2image#68]
I've proceed the instructions for install but while executing the code have following error:

```
>>> from pdf2image import convert_from_path
>>> images = convert_from_path('c:\\Users\\cp\\Python\\QGIS\\Local Plan Policies Map 2018 - Map 3.pdf')
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\pdf2image\pdf2image.py", line 168, in __page_count
    return int(re.search(r'Pages:\s+(\d+)', out.decode("utf8", "ignore")).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\pdf2image\pdf2image.py", line 29, in convert_from_path
    page_count = __page_count(pdf_path, userpw)
  File "C:\Anaconda3\lib\site-packages\pdf2image\pdf2image.py", line 170, in __page_count
    raise Exception('Unable to get page count. %s' % err.decode("utf8", "ignore"))
Exception: Unable to get page count.
>>>
```

I installed packages for Windows. Also tried to install `poppler` package from Python but the environment don't want to make it stick.

```
(base) C:\Users\cp>conda install -c conda-forge poppler
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: C:\Anaconda3

  added / updated specs:
    - poppler


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.3.9   |       hecc5488_0         184 KB  conda-forge
    certifi-2019.3.9           |           py36_0         149 KB  conda-forge
    cryptography-2.6.1         |   py36hb32ad35_0         557 KB  conda-forge
    curl-7.64.1                |       h4496350_0         110 KB  conda-forge
    freetype-2.10.0            |       h5db478b_0         478 KB  conda-forge
    geos-3.7.2                 |       habb2df7_0         1.5 MB  conda-forge
    gettext-0.19.8.1           |    hb01d8f6_1002         5.0 MB  conda-forge
    glib-2.58.3                |    hc0c2ac7_1001         3.4 MB  conda-forge
    jpeg-9c                    |    hfa6e2cd_1001         314 KB  conda-forge
    krb5-1.16.3                |    hdd46e55_1001         819 KB  conda-forge
    libcurl-7.64.1             |       h4496350_0         271 KB  conda-forge
    libffi-3.2.1               |    h6538335_1006          36 KB  conda-forge
    libpng-1.6.37              |       h7602738_0         1.3 MB  conda-forge
    libssh2-1.8.2              |       h642c060_2         186 KB  conda-forge
    matplotlib-3.1.0           |           py36_0           6 KB  conda-forge
    matplotlib-base-3.1.0      |   py36h3e3dc42_0         6.5 MB  conda-forge
    openjpeg-2.3.1             |       ha922770_0         225 KB  conda-forge
    openssl-1.1.1b             |       hfa6e2cd_2         4.8 MB  conda-forge
    pcre-8.41                  |    h6538335_1003         453 KB  conda-forge
    pillow-6.0.0               |   py36h9a613e6_0         674 KB  conda-forge
    poppler-0.77.0             |       h92819f6_0         1.9 MB  conda-forge
    poppler-data-0.4.9         |                1         3.4 MB  conda-forge
    pycurl-7.43.0.2            |   py36h636d3bd_0          66 KB  conda-forge
    qt-5.9.7                   |       hc6833c9_1        91.1 MB  conda-forge
    sqlite-3.28.0              |       hfa6e2cd_0         985 KB  conda-forge
    tk-8.6.9                   |    hfa6e2cd_1001         3.7 MB  conda-forge
    vc-14.1                    |       h0510ff6_4           6 KB
    vs2015_runtime-14.15.26706 |       h3a45250_4         2.4 MB
    ------------------------------------------------------------
                                           Total:       130.3 MB

The following NEW packages will be INSTALLED:

  gettext            conda-forge/win-64::gettext-0.19.8.1-hb01d8f6_1002
  glib               conda-forge/win-64::glib-2.58.3-hc0c2ac7_1001
  krb5               conda-forge/win-64::krb5-1.16.3-hdd46e55_1001
  libffi             conda-forge/win-64::libffi-3.2.1-h6538335_1006
  matplotlib-base    conda-forge/win-64::matplotlib-base-3.1.0-py36h3e3dc42_0
  openjpeg           conda-forge/win-64::openjpeg-2.3.1-ha922770_0
  pcre               conda-forge/win-64::pcre-8.41-h6538335_1003
  poppler            conda-forge/win-64::poppler-0.77.0-h92819f6_0
  poppler-data       conda-forge/noarch::poppler-data-0.4.9-1

The following packages will be REMOVED:

  anaconda-5.2.0-py36_3

The following packages will be UPDATED:

  ca-certificates    anaconda::ca-certificates-2018.03.07-0 --> conda-forge::ca-certificates-2019.3.9-hecc5488_0
  certifi                                  2018.4.16-py36_0 --> 2019.3.9-py36_0
  cryptography       pkgs/main::cryptography-2.2.2-py36hfa~ --> conda-forge::cryptography-2.6.1-py36hb32ad35_0
  curl                    pkgs/main::curl-7.60.0-h7602738_0 --> conda-forge::curl-7.64.1-h4496350_0
  freetype               pkgs/main::freetype-2.8-h51f8f2c_1 --> conda-forge::freetype-2.10.0-h5db478b_0
  geos                                         3.6.0-vc14_0 --> 3.7.2-habb2df7_0
  jpeg                        pkgs/main::jpeg-9b-hb83a4c4_2 --> conda-forge::jpeg-9c-hfa6e2cd_1001
  libcurl              pkgs/main::libcurl-7.60.0-hc4dcbb0_0 --> conda-forge::libcurl-7.64.1-h4496350_0
  libpng                pkgs/main::libpng-1.6.34-h79bbb47_0 --> conda-forge::libpng-1.6.37-h7602738_0
  libssh2               pkgs/main::libssh2-1.8.0-hd619d38_4 --> conda-forge::libssh2-1.8.2-h642c060_2
  matplotlib         pkgs/main::matplotlib-2.2.2-py36h153e~ --> conda-forge::matplotlib-3.1.0-py36_0
  openssl               anaconda::openssl-1.0.2o-h8ea7d77_0 --> conda-forge::openssl-1.1.1b-hfa6e2cd_2
  pillow             pkgs/main::pillow-5.1.0-py36h0738816_0 --> conda-forge::pillow-6.0.0-py36h9a613e6_0
  pycurl             pkgs/main::pycurl-7.43.0.1-py36h74b6d~ --> conda-forge::pycurl-7.43.0.2-py36h636d3bd_0
  qt                     pkgs/main::qt-5.9.5-vc14he4a7d60_0 --> conda-forge::qt-5.9.7-hc6833c9_1
  sqlite                pkgs/main::sqlite-3.23.1-h35aae40_0 --> conda-forge::sqlite-3.28.0-hfa6e2cd_0
  tk                         pkgs/main::tk-8.6.7-hcb92d03_3 --> conda-forge::tk-8.6.9-hfa6e2cd_1001
  vc                                          14-h0510ff6_3 --> 14.1-h0510ff6_4
  vs2015_runtime                               14.0.25123-3 --> 14.15.26706-h3a45250_4


Proceed ([y]/n)?
```

What else can I try?

**Comment by Belval** [comment]
The issue is probably related to how conda installs the `poppler` package.

I am not very familiar with conda, but see if you can manually call `pdfinfo` when you activate the virtual environment. If you cannot, you might want to install it in a more "typical" way using these precompiled binaries: http://blog.alivate.com.au/poppler-windows/

You can just decompress and put them either in your `PATH` or call `pdf2image` with `poppler_path="[Where the binaries are]"`.

**Comment by Belval** [comment]
This might be an issue with conda on Windows, because I can run pdf2image with conda-installed poppler on Ubuntu 18.04 without any issue.

I'll try with my Windows machine later today.

**Comment by Belval** [comment]
I can confirm that this works on my Windows 10 machine. Maybe you just didn't run it with the conda env?

**Comment by rafaleo** [comment]
I don't know but you are probably right it's poppler because scripts finds missing `jepg8.dll` file and it's realy missing from dirs. Instead I found `jpeg62.dll`. Anyway, I'm concerned about the lots of installation packages that conda wants to import and, specifically, this line
```
The following packages will be REMOVED:

  anaconda-5.2.0-py36_3
```
I don't want to uninstall this because it's the core of my env. 

For now found quick workaround with `wand` package. Thanks for reply, I may return later to this if find some solution of my issue.

**Comment by Belval** [comment]
Glad to you found something that works for you.
