### ISSUE TITLE
Problems with output_file

### ISSUE THREAD

**Issue by eamanu** [Belval/pdf2image#69]
Hello, 

I have a PDF file with 10 page, and for a requirements I have to split the pdf file
onto 10 separate-one-page pdf files. I solve that with PyPDF2.

Then, when I try to convert each pdf file to png passing ```output_file=name_page``` I have the next error:

```
Traceback (most recent call last):
  File "medicion.py", line 20, in <module>
    cc.convert_pdf_to_png2()
  File "/home/eamanu/dev/alados-repository/OasisSoftwareAlados/Oasis/PDFConverter.py", line 275, in convert_pdf_to_png2
    output_file=o)
  File "/home/eamanu/dev/alados-repository/OasisSoftwareAlados/venv/lib/python3.7/site-packages/pdf2image/pdf2image.py", line 118, in convert_from_path
    images += _load_from_output_folder(output_folder, uid, in_memory=auto_temp_dir)
  File "/home/eamanu/dev/alados-repository/OasisSoftwareAlados/venv/lib/python3.7/site-packages/pdf2image/pdf2image.py", line 241, in _load_from_output_folder
    images.append(Image.open(os.path.join(output_folder, f)))
  File "/home/eamanu/dev/alados-repository/OasisSoftwareAlados/venv/lib/python3.7/site-packages/PIL/Image.py", line 2705, in open
    % (filename if filename else fp))
OSError: cannot identify image file '/home/eamanu/dev/alados-repository/OasisSoftwareAlados/Oasis/temp/test8.pdf'
```

The algorithms is this:

```
def convert()
        self.split_pdf()  # via PyPDF2
        list_dir = os.listdir(self.working_dir)
        from pdf2image  import convert_from_path
        for ld in list_dir:
            o = ld.split('.')[0]
            print(o)
            convert_from_path(os.path.join(self.working_dir,
                                           ld),
                              output_folder=self.working_dir,
                              fmt='png',
                              thread_count=7,
                              transparent=True,
                              output_file=o)
```

**Comment by eamanu** [comment]
It's weird because test8-1.png is created

**Comment by eamanu** [comment]
It's weird because test8-1.png is created

**Comment by Belval** [comment]
When we added this feature I knew this would happen at some point.

When the conversion is over, `pdf2image` will go through all the files in the directory with the `output_file` prefix, read, and return them.

By using the name of your PDF as the file name, you fall on that edge case. I will see what I can do, but in the meantime add something more to the `output_file` value. It can be anything.
