### ISSUE TITLE
OSError while using convert

### ISSUE THREAD

**Issue by pankhuriagarwal94** [Belval/pdf2image#80]
[Errno 14] Bad address: OSError
Traceback (most recent call last):
File "/var/task/src/decorators.py", line 11, in timed
File "/var/task/src/handler.py", line 185, in preprocessing_handler
File "/var/task/src/decorators.py", line 11, in timed
File "/var/task/src/utils.py", line 407, in convert_format
File "/opt/python/pdf2image/pdf2image.py", line 158, in convert_from_bytes
File "/opt/python/pdf2image/pdf2image.py", line 112, in convert_from_path
File "/var/lang/lib/python3.6/subprocess.py", line 863, in communicate
File "/var/lang/lib/python3.6/subprocess.py", line 1554, in _communicate
data = os.read(key.fd, 32768)
OSError: [Errno 14] Bad address

**Comment by Belval** [comment]
My guess would be that it is running out of memory, but you shouldn't be using `convert_from_bytes` without an `output_folder` in a memory constrained environment like lambda anyway. See [my other repo](https://github.com/Belval/pdf2image-as-a-service) as an example.
